import os
import openpyxl
import xlsxwriter
import clickable_label
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QFileDialog, QMessageBox, QListWidget


class UiQuizMainWindow(object):
    def __init__(self):
        super().__init__()
        QuizMainWindow.setObjectName("QuizMainWindow")
        QuizMainWindow.resize(688, 690)
        QuizMainWindow.setGeometry(800, 300, 500, 500)
        self.quiz_main_widget = QtWidgets.QWidget(QuizMainWindow)
        self.quiz_main_widget.setObjectName("quiz_main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.quiz_main_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.quiz_right_frame = QtWidgets.QFrame(self.quiz_main_widget)
        self.quiz_right_frame.setEnabled(True)
        self.quiz_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quiz_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quiz_right_frame.setObjectName("quiz_right_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.quiz_right_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.answer_a_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.answer_a_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.answer_a_button.setObjectName("answer_a_button")
        self.gridLayout.addWidget(self.answer_a_button, 19, 0, 1, 2)
        self.label_a = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.gridLayout.addWidget(self.label_a, 17, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.main_question_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_question_text_display.sizePolicy().hasHeightForWidth())
        self.main_question_text_display.setSizePolicy(sizePolicy)
        self.main_question_text_display.setMinimumSize(QtCore.QSize(0, 50))
        self.main_question_text_display.setObjectName("main_question_text_display")
        self.gridLayout.addWidget(self.main_question_text_display, 7, 1, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.quiz_right_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 18, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 20, 0, 1, 1)
        self.label_possible_answers = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_possible_answers.setFont(font)
        self.label_possible_answers.setObjectName("label_possible_answers")
        self.gridLayout.addWidget(self.label_possible_answers, 16, 0, 1, 1)
        self.label_number_questions = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_number_questions.setObjectName("label_number_questions")
        self.gridLayout.addWidget(self.label_number_questions, 3, 0, 1, 1)
        self.a_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_text_display.sizePolicy().hasHeightForWidth())
        self.a_text_display.setSizePolicy(sizePolicy)
        self.a_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.a_text_display.setObjectName("a_text_display")
        self.gridLayout.addWidget(self.a_text_display, 18, 0, 1, 2)
        self.label_quiz_details = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_quiz_details.setObjectName("label_quiz_details")
        self.gridLayout.addWidget(self.label_quiz_details, 2, 0, 1, 5)
        self.label_d = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_d.setFont(font)
        self.label_d.setObjectName("label_d")
        self.gridLayout.addWidget(self.label_d, 24, 3, 1, 1)
        self.d_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_text_display.sizePolicy().hasHeightForWidth())
        self.d_text_display.setSizePolicy(sizePolicy)
        self.d_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.d_text_display.setObjectName("d_text_display")
        self.gridLayout.addWidget(self.d_text_display, 25, 3, 1, 2)
        self.Answer_b_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.Answer_b_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.Answer_b_button.setObjectName("Answer_b_button")
        self.gridLayout.addWidget(self.Answer_b_button, 19, 3, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 23, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 15, 0, 1, 1)
        self.answer_c_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.answer_c_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.answer_c_button.setObjectName("answer_c_button")
        self.gridLayout.addWidget(self.answer_c_button, 26, 0, 1, 2)
        self.label_project_title_questionnare = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_title_questionnare.setFont(font)
        self.label_project_title_questionnare.setObjectName("label_project_title_questionnare")
        self.gridLayout.addWidget(self.label_project_title_questionnare, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 22, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 8, 0, 1, 1)
        self.c_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_text_display.sizePolicy().hasHeightForWidth())
        self.c_text_display.setSizePolicy(sizePolicy)
        self.c_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.c_text_display.setObjectName("c_text_display")
        self.gridLayout.addWidget(self.c_text_display, 25, 0, 1, 2)
        self.label_question = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_question.setObjectName("label_question")
        self.gridLayout.addWidget(self.label_question, 7, 0, 1, 1)
        self.label_c = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_c.setFont(font)
        self.label_c.setObjectName("label_c")
        self.gridLayout.addWidget(self.label_c, 24, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.quiz_right_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 25, 2, 1, 1)
        self.quiz_stats_table = QtWidgets.QTableWidget(self.quiz_right_frame)
        self.quiz_stats_table.setAlternatingRowColors(True)
        self.quiz_stats_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.quiz_stats_table.setGridStyle(QtCore.Qt.SolidLine)
        self.quiz_stats_table.setRowCount(1)
        self.quiz_stats_table.setObjectName("quiz_stats_table")
        self.quiz_stats_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(3, item)
        self.quiz_stats_table.horizontalHeader().setCascadingSectionResizes(True)
        self.quiz_stats_table.horizontalHeader().setDefaultSectionSize(110)
        self.quiz_stats_table.horizontalHeader().setSortIndicatorShown(False)
        self.quiz_stats_table.horizontalHeader().setStretchLastSection(True)
        self.quiz_stats_table.verticalHeader().setVisible(False)
        self.quiz_stats_table.verticalHeader().setDefaultSectionSize(35)
        self.quiz_stats_table.verticalHeader().setMinimumSectionSize(30)
        self.quiz_stats_table.verticalHeader().setSortIndicatorShown(False)
        self.quiz_stats_table.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.quiz_stats_table, 29, 0, 1, 5)
        self.answer_d_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.answer_d_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.answer_d_button.setObjectName("answer_d_button")
        self.gridLayout.addWidget(self.answer_d_button, 26, 3, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 13, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 5, 0, 1, 1)
        self.label_stats = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_stats.setObjectName("label_stats")
        self.gridLayout.addWidget(self.label_stats, 28, 0, 1, 1)
        self.label_b = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_b.setFont(font)
        self.label_b.setObjectName("label_b")
        self.gridLayout.addWidget(self.label_b, 17, 3, 1, 1)
        self.b_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_text_display.sizePolicy().hasHeightForWidth())
        self.b_text_display.setSizePolicy(sizePolicy)
        self.b_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.b_text_display.setObjectName("b_text_display")
        self.gridLayout.addWidget(self.b_text_display, 18, 3, 1, 2)
        self.label_average_difficulty = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_average_difficulty.setObjectName("label_average_difficulty")
        self.gridLayout.addWidget(self.label_average_difficulty, 3, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 21, 0, 1, 1)
        self.label_tags_question = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_tags_question.setObjectName("label_tags_question")
        self.gridLayout.addWidget(self.label_tags_question, 9, 0, 1, 1)
        self.cancel_quiz_button = QtWidgets.QPushButton(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancel_quiz_button.setFont(font)
        self.cancel_quiz_button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.cancel_quiz_button.setObjectName("cancel_quiz_button")
        self.gridLayout.addWidget(self.cancel_quiz_button, 30, 4, 1, 1)
        self.finish_quiz_button = QtWidgets.QPushButton(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.finish_quiz_button.setFont(font)
        self.finish_quiz_button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.finish_quiz_button.setCheckable(False)
        self.finish_quiz_button.setAutoDefault(False)
        self.finish_quiz_button.setDefault(False)
        self.finish_quiz_button.setFlat(False)
        self.finish_quiz_button.setObjectName("finish_quiz_button")
        self.gridLayout.addWidget(self.finish_quiz_button, 30, 0, 1, 4)
        self.label_tag_1 = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_tag_1.setEnabled(True)
        self.label_tag_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                       "color: rgb(255, 255, 255);")
        self.label_tag_1.setObjectName("label_tag_1")
        self.gridLayout.addWidget(self.label_tag_1, 9, 1, 1, 1)
        self.label_tag_2 = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_tag_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                       "color: rgb(255, 255, 255);")
        self.label_tag_2.setObjectName("label_tag_2")
        self.gridLayout.addWidget(self.label_tag_2, 9, 3, 1, 1)
        self.gridLayout_2.addWidget(self.quiz_right_frame, 0, 2, 1, 1)
        self.quiz_left_frame = QtWidgets.QFrame(self.quiz_main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.quiz_left_frame.sizePolicy().hasHeightForWidth())
        self.quiz_left_frame.setSizePolicy(sizePolicy)
        self.quiz_left_frame.setMinimumSize(QtCore.QSize(180, 0))
        self.quiz_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quiz_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quiz_left_frame.setObjectName("quiz_left_frame")
        self.formLayout = QtWidgets.QFormLayout(self.quiz_left_frame)
        self.formLayout.setObjectName("formLayout")
        self.new_quiz_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.new_quiz_button.setMinimumSize(QtCore.QSize(45, 50))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.new_quiz_button.setFont(font)
        self.new_quiz_button.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.new_quiz_button.setObjectName("new_quiz_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.new_quiz_button)
        self.label_3 = QtWidgets.QLabel(self.quiz_left_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.restart_quiz_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.restart_quiz_button.setMinimumSize(QtCore.QSize(0, 50))
        self.restart_quiz_button.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.restart_quiz_button.setObjectName("restart_quiz_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.restart_quiz_button)
        self.label_4 = QtWidgets.QLabel(self.quiz_left_frame)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.label_project_nav = QtWidgets.QLabel(self.quiz_left_frame)
        self.label_project_nav.setWordWrap(True)
        self.label_project_nav.setObjectName("label_project_nav")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_project_nav)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem14)
        self.main_list_widget = QtWidgets.QListWidget(self.quiz_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_list_widget.sizePolicy().hasHeightForWidth())
        self.main_list_widget.setSizePolicy(sizePolicy)
        self.main_list_widget.setMinimumSize(QtCore.QSize(81, 0))
        self.main_list_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_list_widget.setLineWidth(3)
        self.main_list_widget.setObjectName("main_list_widget")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.main_list_widget)
        self.change_quiz_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.change_quiz_button.setObjectName("change_quiz_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.change_quiz_button)
        self.go_to_questionnare_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.go_to_questionnare_button.setObjectName("go_to_questionnare_button")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.go_to_questionnare_button)
        self.label_3.raise_()
        self.new_quiz_button.raise_()
        self.restart_quiz_button.raise_()
        self.label_4.raise_()
        self.label_project_nav.raise_()
        self.main_list_widget.raise_()
        self.change_quiz_button.raise_()
        self.go_to_questionnare_button.raise_()
        self.gridLayout_2.addWidget(self.quiz_left_frame, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.quiz_main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        QuizMainWindow.setCentralWidget(self.quiz_main_widget)
        self.quiz_menu_bar = QtWidgets.QMenuBar(QuizMainWindow)
        self.quiz_menu_bar.setGeometry(QtCore.QRect(0, 0, 688, 21))
        self.quiz_menu_bar.setObjectName("quiz_menu_bar")
        QuizMainWindow.setMenuBar(self.quiz_menu_bar)
        self.quiz_status_bar = QtWidgets.QStatusBar(QuizMainWindow)
        self.quiz_status_bar.setObjectName("quiz_status_bar")
        QuizMainWindow.setStatusBar(self.quiz_status_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        self.textify(QuizMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QuizMainWindow)

        # Connections
        self.go_to_questionnare_button.clicked.connect(self.switch_to_questionnare)

    def textify(self, QuizMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QuizMainWindow.setWindowTitle(_translate("QuizMainWindow", "Quiz"))
        self.answer_a_button.setText(_translate("QuizMainWindow", "Answer a)"))
        self.label_a.setText(_translate("QuizMainWindow", "a)"))
        self.label_possible_answers.setText(_translate("QuizMainWindow", "Possible Answers"))
        self.label_number_questions.setText(_translate("QuizMainWindow", "# of questions:"))
        self.label_quiz_details.setText(_translate("QuizMainWindow", "Quiz Details:"))
        self.label_d.setText(_translate("QuizMainWindow", "d)"))
        self.Answer_b_button.setText(_translate("QuizMainWindow", "Answer b)"))
        self.answer_c_button.setText(_translate("QuizMainWindow", "Answer c)"))
        self.label_project_title_questionnare.setText(_translate("QuizMainWindow", "Quiz Title"))
        self.label_question.setText(_translate("QuizMainWindow", "Question:"))
        self.label_c.setText(_translate("QuizMainWindow", "c)"))
        item = self.quiz_stats_table.horizontalHeaderItem(0)
        item.setText(_translate("QuizMainWindow", "Questions"))
        item = self.quiz_stats_table.horizontalHeaderItem(1)
        item.setText(_translate("QuizMainWindow", "Answered"))
        item = self.quiz_stats_table.horizontalHeaderItem(2)
        item.setText(_translate("QuizMainWindow", "Percentage"))
        item = self.quiz_stats_table.horizontalHeaderItem(3)
        item.setText(_translate("QuizMainWindow", "Percentage Correct"))
        self.answer_d_button.setText(_translate("QuizMainWindow", "Answer d)"))
        self.label_stats.setText(_translate("QuizMainWindow", "Stats"))
        self.label_b.setText(_translate("QuizMainWindow", "b)"))
        self.label_average_difficulty.setText(_translate("QuizMainWindow", "Average Difficulty:"))
        self.label_tags_question.setText(_translate("QuizMainWindow", "Tags"))
        self.cancel_quiz_button.setText(_translate("QuizMainWindow", "(X) Cancel"))
        self.finish_quiz_button.setText(_translate("QuizMainWindow", "(✓) Finish Quiz"))
        self.label_tag_1.setText(_translate("QuizMainWindow", "Tag 1"))
        self.label_tag_2.setText(_translate("QuizMainWindow", "Tag 2"))
        self.new_quiz_button.setText(_translate("QuizMainWindow", "(+)"))
        self.label_3.setText(_translate("QuizMainWindow", "New Quiz \n"
                                                          "(This goes first!)"))
        self.restart_quiz_button.setText(_translate("QuizMainWindow", "(<--)"))
        self.label_4.setText(_translate("QuizMainWindow", "Restart current Quiz"))
        self.label_project_nav.setText(_translate("QuizMainWindow", "Click here to navigate through projects:"))
        self.change_quiz_button.setText(_translate("QuizMainWindow", "Change current quiz"))
        self.go_to_questionnare_button.setText(_translate("QuizMainWindow", "Lets prepare more\n"
                                                                            " Questionnares!"))

    @staticmethod
    def switch_to_questionnare():
        QuizMainWindow.hide()
        QuestionnareMainWindow.show()


class UiQuestionnareMainWindow(object):
    def __init__(self):
        super().__init__()
        QuestionnareMainWindow.setObjectName("QuestionnaireMainWindow")
        QuestionnareMainWindow.resize(686, 726)
        QuestionnareMainWindow.setGeometry(800, 300, 500, 500)
        self.questionnare_main_widget = QtWidgets.QWidget(QuestionnareMainWindow)
        self.questionnare_main_widget.setObjectName("questionnaire_main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.questionnare_main_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.questionnare_left_frame = QtWidgets.QFrame(self.questionnare_main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questionnare_left_frame.sizePolicy().hasHeightForWidth())
        self.questionnare_left_frame.setSizePolicy(sizePolicy)
        self.questionnare_left_frame.setMinimumSize(QtCore.QSize(180, 0))
        self.questionnare_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questionnare_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questionnare_left_frame.setObjectName("questionnaire_left_frame")
        self.formLayout = QtWidgets.QFormLayout(self.questionnare_left_frame)
        self.formLayout.setObjectName("formLayout")
        self.new_questionnare_button = QtWidgets.QPushButton(self.questionnare_left_frame)
        self.new_questionnare_button.setMinimumSize(QtCore.QSize(45, 50))
        self.new_questionnare_button.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.new_questionnare_button.setObjectName("new_questionnare_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.new_questionnare_button)
        self.label_new_questionnare = QtWidgets.QLabel(self.questionnare_left_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_new_questionnare.setFont(font)
        self.label_new_questionnare.setWordWrap(True)
        self.label_new_questionnare.setObjectName("label_new_questionnare")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_new_questionnare)
        self.new_question_button = QtWidgets.QPushButton(self.questionnare_left_frame)
        self.new_question_button.setMinimumSize(QtCore.QSize(0, 50))
        self.new_question_button.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.new_question_button.setObjectName("new_question_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.new_question_button)
        self.label_new_question = QtWidgets.QLabel(self.questionnare_left_frame)
        self.label_new_question.setWordWrap(True)
        self.label_new_question.setObjectName("label_new_question")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_new_question)
        self.label_project_nav = QtWidgets.QLabel(self.questionnare_left_frame)
        self.label_project_nav.setWordWrap(True)
        self.label_project_nav.setObjectName("label_project_nav")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_project_nav)
        self.main_list_widget = QtWidgets.QListWidget(self.questionnare_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_list_widget.sizePolicy().hasHeightForWidth())
        self.main_list_widget.setSizePolicy(sizePolicy)
        self.main_list_widget.setMinimumSize(QtCore.QSize(81, 0))
        self.main_list_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_list_widget.setLineWidth(3)
        self.main_list_widget.setObjectName("main_list_widget")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.main_list_widget)
        self.change_quiz_button = QtWidgets.QPushButton(self.questionnare_left_frame)
        self.change_quiz_button.setObjectName("change_quiz_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.change_quiz_button)
        # UI CHANGE ----------------------------------------------------------------------------------------------
        self.modify_questionnare_title_button = QtWidgets.QPushButton()
        self.modify_questionnare_title_button.setText("Modify Questionnare Title")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.modify_questionnare_title_button)
        self.delete_questionnare_button = QtWidgets.QPushButton()
        self.delete_questionnare_button.setText("Delete Questionnare")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.delete_questionnare_button)
        # UI CHANGE FINISH ---------------------------------------------------------------------------------------
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.go_to_quizbutton = QtWidgets.QPushButton(self.questionnare_left_frame)
        self.go_to_quizbutton.setObjectName("go_to_questionnare_button")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.go_to_quizbutton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.gridLayout_2.addWidget(self.questionnare_left_frame, 0, 0, 1, 1)
        self.questionnare_right_frame = QtWidgets.QFrame(self.questionnare_main_widget)
        self.questionnare_right_frame.setEnabled(True)
        self.questionnare_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questionnare_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questionnare_right_frame.setObjectName("questionnare_right_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.questionnare_right_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.alternate_answer_text_edit_3 = QtWidgets.QTextEdit(self.questionnare_right_frame)
        self.alternate_answer_text_edit_3.setEnabled(False)
        self.alternate_answer_text_edit_3.setObjectName("alternate_answer_text_edit_3")
        self.gridLayout.addWidget(self.alternate_answer_text_edit_3, 15, 3, 1, 2)
        self.medium_check_box = QtWidgets.QCheckBox(self.questionnare_right_frame)
        self.medium_check_box.setAutoExclusive(True)
        self.medium_check_box.setObjectName("medium_check_box")
        self.gridLayout.addWidget(self.medium_check_box, 17, 2, 1, 1)
        self.label_number_of_questions = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_number_of_questions.setObjectName("label_number_of_questions")
        self.gridLayout.addWidget(self.label_number_of_questions, 3, 0, 1, 1)
        self.remove_tag_button = QtWidgets.QPushButton(self.questionnare_right_frame)
        self.remove_tag_button.setObjectName("remove_tag_button")
        self.gridLayout.addWidget(self.remove_tag_button, 10, 4, 1, 1)
        self.add_tag_to_question_button = QtWidgets.QPushButton(self.questionnare_right_frame)
        self.add_tag_to_question_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                                      "color: rgb(255, 255, 255);")
        self.add_tag_to_question_button.setObjectName("add_tag_to_question_button")
        self.gridLayout.addWidget(self.add_tag_to_question_button, 9, 4, 1, 1)
        self.label_tags = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_tags.setObjectName("label_tags")
        self.gridLayout.addWidget(self.label_tags, 9, 0, 1, 1)
        self.answer_text_edit = QtWidgets.QTextEdit(self.questionnare_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_text_edit.sizePolicy().hasHeightForWidth())
        self.answer_text_edit.setSizePolicy(sizePolicy)
        self.answer_text_edit.setMinimumSize(QtCore.QSize(0, 150))
        self.answer_text_edit.setObjectName("answer_text_edit")
        self.gridLayout.addWidget(self.answer_text_edit, 12, 0, 1, 5)
        self.add_question_button = QtWidgets.QPushButton(self.questionnare_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_question_button.setFont(font)
        self.add_question_button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.add_question_button.setCheckable(False)
        self.add_question_button.setAutoDefault(False)
        self.add_question_button.setDefault(False)
        self.add_question_button.setFlat(False)
        self.add_question_button.setObjectName("add_question_button")
        self.gridLayout.addWidget(self.add_question_button, 18, 0, 1, 4)
        self.add_tag_button = QtWidgets.QPushButton(self.questionnare_right_frame)
        self.add_tag_button.setObjectName("add_tag_button")
        self.gridLayout.addWidget(self.add_tag_button, 10, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 1)
        self.tag_combo_box = QtWidgets.QComboBox(self.questionnare_right_frame)
        self.tag_combo_box.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                         "color: rgb(255, 255, 255);")
        self.tag_combo_box.setObjectName("tag_combo_box")
        self.gridLayout.addWidget(self.tag_combo_box, 9, 1, 1, 3)
        self.easy_check_box = QtWidgets.QCheckBox(self.questionnare_right_frame)
        self.easy_check_box.setChecked(True)
        self.easy_check_box.setAutoExclusive(True)
        self.easy_check_box.setObjectName("easy_check_box")
        self.gridLayout.addWidget(self.easy_check_box, 17, 0, 1, 1)
        self.label_average_difficulty = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_average_difficulty.setObjectName("label_average_difficulty")
        self.gridLayout.addWidget(self.label_average_difficulty, 3, 3, 1, 1)
        self.label_project_title_questionnare = QtWidgets.QLabel(self.questionnare_right_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_title_questionnare.setFont(font)
        self.label_project_title_questionnare.setObjectName("label_project_title_questionnare")
        self.gridLayout.addWidget(self.label_project_title_questionnare, 0, 0, 1, 3)
        self.alternate_answer_text_edit_2 = QtWidgets.QTextEdit(self.questionnare_right_frame)
        self.alternate_answer_text_edit_2.setEnabled(False)
        self.alternate_answer_text_edit_2.setObjectName("alternate_answer_text_edit_2")
        self.gridLayout.addWidget(self.alternate_answer_text_edit_2, 15, 0, 1, 3)
        self.label_remove_tag = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_remove_tag.setObjectName("label_remove_tag")
        self.gridLayout.addWidget(self.label_remove_tag, 10, 3, 1, 1)
        self.possible_wrong_answers_check_box = QtWidgets.QCheckBox(self.questionnare_right_frame)
        self.possible_wrong_answers_check_box.setMinimumSize(QtCore.QSize(0, 32))
        self.possible_wrong_answers_check_box.setIconSize(QtCore.QSize(16, 32))
        self.possible_wrong_answers_check_box.setObjectName("possible_wrong_answers_check_box")
        self.gridLayout.addWidget(self.possible_wrong_answers_check_box, 14, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 6, 0, 1, 1)
        self.question_line_edit = QtWidgets.QLineEdit(self.questionnare_right_frame)
        self.question_line_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.question_line_edit.setText("")
        self.question_line_edit.setObjectName("question_line_edit")
        self.gridLayout.addWidget(self.question_line_edit, 8, 0, 1, 5)
        self.label_questionnare_details = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_questionnare_details.setObjectName("label_questionnaire_details")
        self.gridLayout.addWidget(self.label_questionnare_details, 2, 0, 1, 5)
        self.label_add_tag = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_add_tag.setObjectName("label_add_tag")
        self.gridLayout.addWidget(self.label_add_tag, 10, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(self.questionnare_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 18, 4, 1, 1)
        self.alternate_answer_text_edit_1 = QtWidgets.QTextEdit(self.questionnare_right_frame)
        self.alternate_answer_text_edit_1.setEnabled(False)
        self.alternate_answer_text_edit_1.setObjectName("alternate_answer_text_edit_1")
        self.gridLayout.addWidget(self.alternate_answer_text_edit_1, 14, 3, 1, 2)
        self.label_answer = QtWidgets.QLabel(self.questionnare_right_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_answer.setFont(font)
        self.label_answer.setObjectName("label_answer")
        self.gridLayout.addWidget(self.label_answer, 11, 0, 1, 1)
        self.label_question = QtWidgets.QLabel(self.questionnare_right_frame)
        self.label_question.setObjectName("label_question")
        self.gridLayout.addWidget(self.label_question, 7, 0, 1, 1)
        self.expert_check_box = QtWidgets.QCheckBox(self.questionnare_right_frame)
        self.expert_check_box.setAutoExclusive(True)
        self.expert_check_box.setObjectName("expert_check_box")
        self.gridLayout.addWidget(self.expert_check_box, 17, 4, 1, 1)
        self.hard_check_box = QtWidgets.QCheckBox(self.questionnare_right_frame)
        self.hard_check_box.setAutoExclusive(True)
        self.hard_check_box.setObjectName("hard_check_box")
        self.gridLayout.addWidget(self.hard_check_box, 17, 3, 1, 1)
        self.gridLayout_2.addWidget(self.questionnare_right_frame, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.questionnare_main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        QuestionnareMainWindow.setCentralWidget(self.questionnare_main_widget)
        self.questionnare_menu_bar = QtWidgets.QMenuBar(QuestionnareMainWindow)
        self.questionnare_menu_bar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.questionnare_menu_bar.setObjectName("questionnare_menu_bar")
        QuestionnareMainWindow.setMenuBar(self.questionnare_menu_bar)
        self.questionnare_status_bar = QtWidgets.QStatusBar(QuestionnareMainWindow)
        self.questionnare_status_bar.setObjectName("questionnare_status_bar")
        QuestionnareMainWindow.setStatusBar(self.questionnare_status_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.textify(QuestionnareMainWindow)
        self.possible_wrong_answers_check_box.toggled['bool'].connect(self.alternate_answer_text_edit_1.setEnabled)
        self.possible_wrong_answers_check_box.toggled['bool'].connect(self.alternate_answer_text_edit_2.setEnabled)
        self.possible_wrong_answers_check_box.toggled['bool'].connect(self.alternate_answer_text_edit_3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(QuestionnareMainWindow)

        # Additional init
        self.path = os.getcwd()
        for file in os.listdir():  # Adds current saved quizzes to main list widget
            if file.startswith("Quiz"):
                self.main_list_widget.addItem(file[5:-5])
        if self.main_list_widget.count() == 0:
            self.questionnare_right_frame.setEnabled(False)
        else:
            self.questionnare_status_bar.showMessage(f"Active Questionnare: {self.main_list_widget.item(0).text()}")
            self.active_questionnare = self.main_list_widget.item(0).text()
            self.label_project_title_questionnare.setText(self.active_questionnare)
            self.label_number_of_questions.setText("# of questions: 0")
            self.label_average_difficulty.setText("Average Difficulty: Pending...")
            self.questionnare_status_bar.showMessage(f"Active Questionnare: {self.active_questionnare}")

        # Class Variables
        self.window = QtWidgets.QWidget()
        self.window.setGeometry(800, 300, 500, 500)

        # UI changes
        self.menuOpciones = QtWidgets.QMenu(self.questionnare_menu_bar)
        self.menuOpciones.setTitle("Opciones")

        # Connections
        self.go_to_quizbutton.clicked.connect(self.switch_to_quiz)
        self.new_questionnare_button.clicked.connect(self.new_questionnare)
        self.modify_questionnare_title_button.clicked.connect(self.modify_title)
        self.delete_questionnare_button.clicked.connect(self.delete_questionnare)
        self.new_question_button.clicked.connect(self.new_question)

    def textify(self, QuestionnareMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QuestionnareMainWindow.setWindowTitle(_translate("QuestionnaireMainWindow", "Questionnare"))
        self.new_questionnare_button.setText(_translate("QuestionnaireMainWindow", "(+)"))
        self.label_new_questionnare.setText(_translate("QuestionnaireMainWindow", "New Questionnare \n"
                                                                                  "(This goes first!)"))
        self.new_question_button.setText(_translate("QuestionnaireMainWindow", "(+++)"))
        self.label_new_question.setText(_translate("QuestionnaireMainWindow", "New Question"))
        self.label_project_nav.setText(
            _translate("QuestionnaireMainWindow", "Click here to navigate through projects:"))
        self.change_quiz_button.setText(_translate("QuestionnaireMainWindow", "Select current questionnare"))
        self.go_to_quizbutton.setText(_translate("QuestionnaireMainWindow", "Lets take a\n"
                                                                            " Quiz!"))
        self.medium_check_box.setText(_translate("QuestionnaireMainWindow", "Medium (+3 points)"))
        self.label_number_of_questions.setText(_translate("QuestionnaireMainWindow", "# of questions:"))
        self.remove_tag_button.setText(_translate("QuestionnaireMainWindow", "(-)"))
        self.add_tag_to_question_button.setText(_translate("QuestionnaireMainWindow", "Add tag >"))
        self.label_tags.setText(_translate("QuestionnaireMainWindow", "Tags"))
        self.add_question_button.setText(_translate("QuestionnaireMainWindow", "(✓) Add Question!"))
        self.add_tag_button.setText(_translate("QuestionnaireMainWindow", "(+)"))
        self.easy_check_box.setText(_translate("QuestionnaireMainWindow", "Easy (+1 point)"))
        self.label_average_difficulty.setText(_translate("QuestionnaireMainWindow", "Average Difficulty:"))
        self.label_project_title_questionnare.setText(_translate("QuestionnaireMainWindow", "Questionnare Title"))
        self.label_remove_tag.setText(_translate("QuestionnaireMainWindow", "Remove Tag"))
        self.possible_wrong_answers_check_box.setText(_translate("QuestionnaireMainWindow", "Possible Wrong Answers"))
        self.label_questionnare_details.setText(_translate("QuestionnaireMainWindow", "Questionnare Details:"))
        self.label_add_tag.setText(_translate("QuestionnaireMainWindow", "Add Tag"))
        self.cancel_button.setText(_translate("QuestionnaireMainWindow", "(X) Cancel"))
        self.label_answer.setText(_translate("QuestionnaireMainWindow", "Answer"))
        self.label_question.setText(_translate("QuestionnaireMainWindow", "Question"))
        self.expert_check_box.setText(_translate("QuestionnaireMainWindow", "Expert (+7 points)"))
        self.hard_check_box.setText(_translate("QuestionnaireMainWindow", "Hard (+5 points)"))

    @staticmethod
    def switch_to_quiz():
        QuestionnareMainWindow.close()
        QuizMainWindow.show()

    def new_questionnare(self):
        quiz_title, ok = QtWidgets.QInputDialog.getText(self.window, "Create a Quiz", "Select a title for your "
                                                                                      "questionnare: ",
                                                        QtWidgets.QLineEdit.Normal)
        if ok and quiz_title:
            wb = xlsxwriter.Workbook(f"Quiz_{quiz_title}.xlsx")
            wb.close()
            questionnare_ui.__init__()

    def new_question(self):
        if self.main_list_widget.count() == 0:
            ask = QtWidgets.QMessageBox.question(self.window, "No quiz created", "It appears you have not created "
                                                                                 "a quiz yet to assign this question\n"
                                                                                 "\nWould you like to create one now?")
            if ask == QMessageBox.Yes:
                self.new_questionnare()

    def modify_title(self):
        window = QtWidgets.QWidget()
        window.setGeometry(800, 300, 500, 500)
        new_title, ok = QtWidgets.QInputDialog.getText(window, "Change Questionnare Title",
                                                       'Select new questionnare title',
                                                       QtWidgets.QLineEdit.Normal)
        if new_title and ok:
            old_title = f"Quiz_{self.main_list_widget.selectedItems()[0].text()}.xlsx"
            new_title = f"Quiz_{new_title}.xlsx"
            wb = openpyxl.load_workbook(old_title)
            wb.save(new_title)
            wb.close()
            os.remove(old_title)
            questionnare_ui.__init__()

    def delete_questionnare(self):
        confirmation = QtWidgets.QMessageBox.question(self.window, "Confirmation",
                                                      "Are you sure you want to permanently delete this questionnare:")
        if confirmation == QMessageBox.Yes:
            deleted_quiz = f"Quiz_{self.main_list_widget.selectedItems()[0].text()}.xlsx"
            os.remove(deleted_quiz)
            questionnare_ui.__init__()
        else:
            self.generic_information("", "Questionnare was not deleted.")

    @staticmethod
    def generic_information(title="Information", text="Details", icon=QMessageBox.Information):
        parent = QtWidgets.QMessageBox()
        parent.setGeometry(800, 300, 500, 500)
        parent.setWindowTitle(title)
        parent.setText(text)
        parent.setIcon(icon)
        parent.exec_()

    @staticmethod
    def generic_error(title="Error", text="Error Details", icon=QMessageBox.Information):
        parent = QtWidgets.QMessageBox()
        parent.setGeometry(800, 300, 500, 500)
        parent.setWindowTitle(title)
        parent.setText(text)
        parent.setIcon(icon)
        parent.exec_()


class QuizzerMainWindow(object):
    def __init__(self):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 492)
        MainWindow.setGeometry(800, 300, 500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.home_frame = QtWidgets.QFrame(self.centralwidget)
        self.home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_frame.setObjectName("home_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pix_label_questionnare = clickable_label.QClickableLabel(self.home_frame)
        self.pix_label_questionnare.setMinimumSize(QtCore.QSize(215, 215))
        self.pix_label_questionnare.setAutoFillBackground(False)
        self.pix_label_questionnare.setFrameShape(QtWidgets.QFrame.Panel)
        self.pix_label_questionnare.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pix_label_questionnare.setLineWidth(5)
        self.pix_label_questionnare.setMidLineWidth(0)
        self.pix_label_questionnare.setText("")
        self.pix_label_questionnare.setPixmap(QtGui.QPixmap("questionnare.gif"))
        self.pix_label_questionnare.setAlignment(QtCore.Qt.AlignCenter)
        self.pix_label_questionnare.setObjectName("pix_label_questionnare")
        self.gridLayout_2.addWidget(self.pix_label_questionnare, 1, 0, 1, 1)
        self.label_questionnare = QtWidgets.QLabel(self.home_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_questionnare.setFont(font)
        self.label_questionnare.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionnare.setObjectName("label_questionnare")
        self.gridLayout_2.addWidget(self.label_questionnare, 2, 0, 1, 1)
        self.label_quiz = QtWidgets.QLabel(self.home_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_quiz.setFont(font)
        self.label_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quiz.setObjectName("label_quiz")
        self.gridLayout_2.addWidget(self.label_quiz, 2, 2, 1, 1)
        self.pix_label_quiz = clickable_label.QClickableLabel(self.home_frame)
        self.pix_label_quiz.setMinimumSize(QtCore.QSize(215, 215))
        self.pix_label_quiz.setFrameShape(QtWidgets.QFrame.Panel)
        self.pix_label_quiz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pix_label_quiz.setLineWidth(5)
        self.pix_label_quiz.setText("")
        self.pix_label_quiz.setPixmap(QtGui.QPixmap("quiz-icon.gif"))
        self.pix_label_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.pix_label_quiz.setObjectName("pix_label_quiz")
        self.gridLayout_2.addWidget(self.pix_label_quiz, 1, 2, 1, 1)
        self.label_home_title = QtWidgets.QLabel(self.home_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_home_title.sizePolicy().hasHeightForWidth())
        self.label_home_title.setSizePolicy(sizePolicy)
        self.label_home_title.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_home_title.setFont(font)
        self.label_home_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_home_title.setObjectName("label_home_title")
        self.gridLayout_2.addWidget(self.label_home_title, 0, 0, 1, 3)
        self.label_questionnare_description = QtWidgets.QLabel(self.home_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_questionnare_description.sizePolicy().hasHeightForWidth())
        self.label_questionnare_description.setSizePolicy(sizePolicy)
        self.label_questionnare_description.setMinimumSize(QtCore.QSize(0, 20))
        self.label_questionnare_description.setWordWrap(True)
        self.label_questionnare_description.setObjectName("label_questionnare_description")
        self.gridLayout_2.addWidget(self.label_questionnare_description, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.home_frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 3, 1)
        self.label_quizzes_description = QtWidgets.QLabel(self.home_frame)
        self.label_quizzes_description.setObjectName("label_quizzes_description")
        self.gridLayout_2.addWidget(self.label_quizzes_description, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.home_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.textify(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connections
        self.pix_label_questionnare.clicked.connect(self.show_questionnare)
        self.pix_label_quiz.clicked.connect(self.show_quiz)
        self.pix_label_questionnare.clicked.connect(self.show_questionnare)

    def textify(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quizzer App"))
        self.label_questionnare.setText(_translate("MainWindow", "Questionnares"))
        self.label_quiz.setText(_translate("MainWindow", "Quizzes"))
        self.label_home_title.setText(_translate("MainWindow", "Quizzes App"))
        self.label_questionnare_description.setText(_translate("MainWindow", "Create your own questionnares and "
                                                                             "prepare them to transform into "
                                                                             "quizzes!"))
        self.label_quizzes_description.setText(_translate("MainWindow", "Test your own quizzes!"))

    def show_quiz(self):
        MainWindow.close()
        QuizMainWindow.show()

    def show_questionnare(self):
        MainWindow.close()
        QuestionnareMainWindow.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    quizzer_ui = QuizzerMainWindow()
    quizzer_ui.__init__()
    MainWindow.show()
    QuizMainWindow = QtWidgets.QMainWindow()
    quiz_ui = UiQuizMainWindow()
    quiz_ui.__init__()
    QuestionnareMainWindow = QtWidgets.QMainWindow()
    questionnare_ui = UiQuestionnareMainWindow()
    questionnare_ui.__init__()
    sys.exit(app.exec_())
