import clickable_label
import quiz
import questionnare
from PyQt5 import QtCore, QtGui, QtWidgets


class QuizzerMainWindow(object):
    def __init__(self):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 492)
        MainWindow.setGeometry(800, 300, 500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.home_frame = QtWidgets.QFrame(self.centralwidget)
        self.home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_frame.setObjectName("home_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pix_label_questionnare = clickable_label.QClickableLabel(self.home_frame)
        self.pix_label_questionnare.setMinimumSize(QtCore.QSize(215, 215))
        self.pix_label_questionnare.setAutoFillBackground(False)
        self.pix_label_questionnare.setFrameShape(QtWidgets.QFrame.Panel)
        self.pix_label_questionnare.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pix_label_questionnare.setLineWidth(5)
        self.pix_label_questionnare.setMidLineWidth(0)
        self.pix_label_questionnare.setText("")
        self.pix_label_questionnare.setPixmap(QtGui.QPixmap("questionnare.gif"))
        self.pix_label_questionnare.setAlignment(QtCore.Qt.AlignCenter)
        self.pix_label_questionnare.setObjectName("pix_label_questionnare")
        self.gridLayout_2.addWidget(self.pix_label_questionnare, 1, 0, 1, 1)
        self.label_questionnare = QtWidgets.QLabel(self.home_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_questionnare.setFont(font)
        self.label_questionnare.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionnare.setObjectName("label_questionnare")
        self.gridLayout_2.addWidget(self.label_questionnare, 2, 0, 1, 1)
        self.label_quiz = QtWidgets.QLabel(self.home_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_quiz.setFont(font)
        self.label_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quiz.setObjectName("label_quiz")
        self.gridLayout_2.addWidget(self.label_quiz, 2, 2, 1, 1)
        self.pix_label_quiz = clickable_label.QClickableLabel(self.home_frame)
        self.pix_label_quiz.setMinimumSize(QtCore.QSize(215, 215))
        self.pix_label_quiz.setFrameShape(QtWidgets.QFrame.Panel)
        self.pix_label_quiz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pix_label_quiz.setLineWidth(5)
        self.pix_label_quiz.setText("")
        self.pix_label_quiz.setPixmap(QtGui.QPixmap("quiz-icon.gif"))
        self.pix_label_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.pix_label_quiz.setObjectName("pix_label_quiz")
        self.gridLayout_2.addWidget(self.pix_label_quiz, 1, 2, 1, 1)
        self.label_home_title = QtWidgets.QLabel(self.home_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_home_title.sizePolicy().hasHeightForWidth())
        self.label_home_title.setSizePolicy(sizePolicy)
        self.label_home_title.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_home_title.setFont(font)
        self.label_home_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_home_title.setObjectName("label_home_title")
        self.gridLayout_2.addWidget(self.label_home_title, 0, 0, 1, 3)
        self.label_questionnare_description = QtWidgets.QLabel(self.home_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_questionnare_description.sizePolicy().hasHeightForWidth())
        self.label_questionnare_description.setSizePolicy(sizePolicy)
        self.label_questionnare_description.setMinimumSize(QtCore.QSize(0, 20))
        self.label_questionnare_description.setWordWrap(True)
        self.label_questionnare_description.setObjectName("label_questionnare_description")
        self.gridLayout_2.addWidget(self.label_questionnare_description, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.home_frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 3, 1)
        self.label_quizzes_description = QtWidgets.QLabel(self.home_frame)
        self.label_quizzes_description.setObjectName("label_quizzes_description")
        self.gridLayout_2.addWidget(self.label_quizzes_description, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.home_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.textify(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connections
        self.pix_label_questionnare.clicked.connect(self.show_questionnare)
        self.pix_label_quiz.clicked.connect(self.show_quiz)

    def textify(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quizzer App"))
        self.label_questionnare.setText(_translate("MainWindow", "Questionnares"))
        self.label_quiz.setText(_translate("MainWindow", "Quizzes"))
        self.label_home_title.setText(_translate("MainWindow", "Quizzes App"))
        self.label_questionnare_description.setText(_translate("MainWindow", "Create your own questionnares and "
                                                                             "prepare them to transform into "
                                                                             "quizzes!"))
        self.label_quizzes_description.setText(_translate("MainWindow", "Test your own quizzes!"))

    def show_questionnare(self):
        print("Showing questionnare...")

    def show_quiz(self):
        print("Showing quiz...")
        MainWindow.hide()
        question = quiz.UiQuizMainWindow()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = QuizzerMainWindow()
    ui.__init__()
    MainWindow.show()
    sys.exit(app.exec_())
