# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quizzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickable_label import QClickableLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setMinimumSize(QtCore.QSize(885, 20))
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 1, 0, 1, 1)
        self.home_frame = QtWidgets.QFrame(self.centralwidget)
        self.home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_frame.setObjectName("home_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pix_label_questionnare = QClickableLabel(self.home_frame)
        self.pix_label_questionnare.setMinimumSize(QtCore.QSize(215, 215))
        self.pix_label_questionnare.setAutoFillBackground(False)
        self.pix_label_questionnare.setFrameShape(QtWidgets.QFrame.Panel)
        self.pix_label_questionnare.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pix_label_questionnare.setLineWidth(5)
        self.pix_label_questionnare.setMidLineWidth(0)
        self.pix_label_questionnare.setText("")
        self.pix_label_questionnare.setPixmap(QtGui.QPixmap("questionnare.gif"))
        self.pix_label_questionnare.setAlignment(QtCore.Qt.AlignCenter)
        self.pix_label_questionnare.setObjectName("pix_label_questionnare")
        self.gridLayout_2.addWidget(self.pix_label_questionnare, 1, 0, 1, 1)
        self.label_questionnare = QtWidgets.QLabel(self.home_frame)
        self.label_questionnare.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionnare.setObjectName("label_questionnare")
        self.gridLayout_2.addWidget(self.label_questionnare, 2, 0, 1, 1)
        self.label_quiz = QtWidgets.QLabel(self.home_frame)
        self.label_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quiz.setObjectName("label_quiz")
        self.gridLayout_2.addWidget(self.label_quiz, 2, 2, 1, 1)
        self.pix_label_quiz = QClickableLabel(self.home_frame)
        self.pix_label_quiz.setMinimumSize(QtCore.QSize(215, 215))
        self.pix_label_quiz.setFrameShape(QtWidgets.QFrame.Panel)
        self.pix_label_quiz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pix_label_quiz.setLineWidth(5)
        self.pix_label_quiz.setText("")
        self.pix_label_quiz.setPixmap(QtGui.QPixmap("ezgif.com-gif-maker.gif"))
        self.pix_label_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.pix_label_quiz.setObjectName("pix_label_quiz")
        self.gridLayout_2.addWidget(self.pix_label_quiz, 1, 2, 1, 1)
        self.label_home_title = QtWidgets.QLabel(self.home_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_home_title.sizePolicy().hasHeightForWidth())
        self.label_home_title.setSizePolicy(sizePolicy)
        self.label_home_title.setMinimumSize(QtCore.QSize(0, 100))
        self.label_home_title.setObjectName("label_home_title")
        self.gridLayout_2.addWidget(self.label_home_title, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.home_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.home_frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 3, 1)
        self.label_2 = QtWidgets.QLabel(self.home_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.home_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.showMessage("Ready", 5000)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pix_label_questionnare.clicked.connect(self.label_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_status.setText(_translate("MainWindow", "Status"))
        self.label_questionnare.setText(_translate("MainWindow", "Questionnares"))
        self.label_quiz.setText(_translate("MainWindow", "Quizzes"))
        self.label_home_title.setText(_translate("MainWindow", "Quizzes App"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))

    def label_clicked(self):
        print("This works!")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
