from PyQt5 import QtCore, QtGui, QtWidgets


class UiQuizMainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        QuizMainWindow.setObjectName("QuizMainWindow")
        QuizMainWindow.resize(688, 690)
        QuizMainWindow.setGeometry(800, 300, 500, 500)
        self.quiz_main_widget = QtWidgets.QWidget(QuizMainWindow)
        self.quiz_main_widget.setObjectName("quiz_main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.quiz_main_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.quiz_right_frame = QtWidgets.QFrame(self.quiz_main_widget)
        self.quiz_right_frame.setEnabled(True)
        self.quiz_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quiz_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quiz_right_frame.setObjectName("quiz_right_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.quiz_right_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.answer_a_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.answer_a_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.answer_a_button.setObjectName("answer_a_button")
        self.gridLayout.addWidget(self.answer_a_button, 19, 0, 1, 2)
        self.label_a = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.gridLayout.addWidget(self.label_a, 17, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.main_question_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_question_text_display.sizePolicy().hasHeightForWidth())
        self.main_question_text_display.setSizePolicy(sizePolicy)
        self.main_question_text_display.setMinimumSize(QtCore.QSize(0, 50))
        self.main_question_text_display.setObjectName("main_question_text_display")
        self.gridLayout.addWidget(self.main_question_text_display, 7, 1, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.quiz_right_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 18, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 20, 0, 1, 1)
        self.label_possible_answers = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_possible_answers.setFont(font)
        self.label_possible_answers.setObjectName("label_possible_answers")
        self.gridLayout.addWidget(self.label_possible_answers, 16, 0, 1, 1)
        self.label_number_questions = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_number_questions.setObjectName("label_number_questions")
        self.gridLayout.addWidget(self.label_number_questions, 3, 0, 1, 1)
        self.a_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_text_display.sizePolicy().hasHeightForWidth())
        self.a_text_display.setSizePolicy(sizePolicy)
        self.a_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.a_text_display.setObjectName("a_text_display")
        self.gridLayout.addWidget(self.a_text_display, 18, 0, 1, 2)
        self.label_quiz_details = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_quiz_details.setObjectName("label_quiz_details")
        self.gridLayout.addWidget(self.label_quiz_details, 2, 0, 1, 5)
        self.label_d = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_d.setFont(font)
        self.label_d.setObjectName("label_d")
        self.gridLayout.addWidget(self.label_d, 24, 3, 1, 1)
        self.d_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_text_display.sizePolicy().hasHeightForWidth())
        self.d_text_display.setSizePolicy(sizePolicy)
        self.d_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.d_text_display.setObjectName("d_text_display")
        self.gridLayout.addWidget(self.d_text_display, 25, 3, 1, 2)
        self.Answer_b_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.Answer_b_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.Answer_b_button.setObjectName("Answer_b_button")
        self.gridLayout.addWidget(self.Answer_b_button, 19, 3, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 23, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 15, 0, 1, 1)
        self.answer_c_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.answer_c_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.answer_c_button.setObjectName("answer_c_button")
        self.gridLayout.addWidget(self.answer_c_button, 26, 0, 1, 2)
        self.label_project_title_questionnare = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_title_questionnare.setFont(font)
        self.label_project_title_questionnare.setObjectName("label_project_title_questionnare")
        self.gridLayout.addWidget(self.label_project_title_questionnare, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 22, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 8, 0, 1, 1)
        self.c_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_text_display.sizePolicy().hasHeightForWidth())
        self.c_text_display.setSizePolicy(sizePolicy)
        self.c_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.c_text_display.setObjectName("c_text_display")
        self.gridLayout.addWidget(self.c_text_display, 25, 0, 1, 2)
        self.label_question = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_question.setObjectName("label_question")
        self.gridLayout.addWidget(self.label_question, 7, 0, 1, 1)
        self.label_c = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_c.setFont(font)
        self.label_c.setObjectName("label_c")
        self.gridLayout.addWidget(self.label_c, 24, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.quiz_right_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 25, 2, 1, 1)
        self.quiz_stats_table = QtWidgets.QTableWidget(self.quiz_right_frame)
        self.quiz_stats_table.setAlternatingRowColors(True)
        self.quiz_stats_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.quiz_stats_table.setGridStyle(QtCore.Qt.SolidLine)
        self.quiz_stats_table.setRowCount(1)
        self.quiz_stats_table.setObjectName("quiz_stats_table")
        self.quiz_stats_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.quiz_stats_table.setHorizontalHeaderItem(3, item)
        self.quiz_stats_table.horizontalHeader().setCascadingSectionResizes(True)
        self.quiz_stats_table.horizontalHeader().setDefaultSectionSize(110)
        self.quiz_stats_table.horizontalHeader().setSortIndicatorShown(False)
        self.quiz_stats_table.horizontalHeader().setStretchLastSection(True)
        self.quiz_stats_table.verticalHeader().setVisible(False)
        self.quiz_stats_table.verticalHeader().setDefaultSectionSize(35)
        self.quiz_stats_table.verticalHeader().setMinimumSectionSize(30)
        self.quiz_stats_table.verticalHeader().setSortIndicatorShown(False)
        self.quiz_stats_table.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.quiz_stats_table, 29, 0, 1, 5)
        self.answer_d_button = QtWidgets.QPushButton(self.quiz_right_frame)
        self.answer_d_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "color: rgb(255, 255, 255);")
        self.answer_d_button.setObjectName("answer_d_button")
        self.gridLayout.addWidget(self.answer_d_button, 26, 3, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 13, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 5, 0, 1, 1)
        self.label_stats = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_stats.setObjectName("label_stats")
        self.gridLayout.addWidget(self.label_stats, 28, 0, 1, 1)
        self.label_b = QtWidgets.QLabel(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_b.setFont(font)
        self.label_b.setObjectName("label_b")
        self.gridLayout.addWidget(self.label_b, 17, 3, 1, 1)
        self.b_text_display = QtWidgets.QTextBrowser(self.quiz_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_text_display.sizePolicy().hasHeightForWidth())
        self.b_text_display.setSizePolicy(sizePolicy)
        self.b_text_display.setMinimumSize(QtCore.QSize(220, 0))
        self.b_text_display.setObjectName("b_text_display")
        self.gridLayout.addWidget(self.b_text_display, 18, 3, 1, 2)
        self.label_average_difficulty = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_average_difficulty.setObjectName("label_average_difficulty")
        self.gridLayout.addWidget(self.label_average_difficulty, 3, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 21, 0, 1, 1)
        self.label_tags_question = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_tags_question.setObjectName("label_tags_question")
        self.gridLayout.addWidget(self.label_tags_question, 9, 0, 1, 1)
        self.cancel_quiz_button = QtWidgets.QPushButton(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancel_quiz_button.setFont(font)
        self.cancel_quiz_button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.cancel_quiz_button.setObjectName("cancel_quiz_button")
        self.gridLayout.addWidget(self.cancel_quiz_button, 30, 4, 1, 1)
        self.dinish_quiz_button = QtWidgets.QPushButton(self.quiz_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dinish_quiz_button.setFont(font)
        self.dinish_quiz_button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.dinish_quiz_button.setCheckable(False)
        self.dinish_quiz_button.setAutoDefault(False)
        self.dinish_quiz_button.setDefault(False)
        self.dinish_quiz_button.setFlat(False)
        self.dinish_quiz_button.setObjectName("dinish_quiz_button")
        self.gridLayout.addWidget(self.dinish_quiz_button, 30, 0, 1, 4)
        self.label_tag_1 = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_tag_1.setEnabled(True)
        self.label_tag_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                       "color: rgb(255, 255, 255);")
        self.label_tag_1.setObjectName("label_tag_1")
        self.gridLayout.addWidget(self.label_tag_1, 9, 1, 1, 1)
        self.label_tag_2 = QtWidgets.QLabel(self.quiz_right_frame)
        self.label_tag_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                       "color: rgb(255, 255, 255);")
        self.label_tag_2.setObjectName("label_tag_2")
        self.gridLayout.addWidget(self.label_tag_2, 9, 3, 1, 1)
        self.gridLayout_2.addWidget(self.quiz_right_frame, 0, 2, 1, 1)
        self.quiz_left_frame = QtWidgets.QFrame(self.quiz_main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.quiz_left_frame.sizePolicy().hasHeightForWidth())
        self.quiz_left_frame.setSizePolicy(sizePolicy)
        self.quiz_left_frame.setMinimumSize(QtCore.QSize(180, 0))
        self.quiz_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quiz_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quiz_left_frame.setObjectName("quiz_left_frame")
        self.formLayout = QtWidgets.QFormLayout(self.quiz_left_frame)
        self.formLayout.setObjectName("formLayout")
        self.new_quiz_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.new_quiz_button.setMinimumSize(QtCore.QSize(45, 50))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.new_quiz_button.setFont(font)
        self.new_quiz_button.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.new_quiz_button.setObjectName("new_quiz_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.new_quiz_button)
        self.label_3 = QtWidgets.QLabel(self.quiz_left_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.restart_quiz_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.restart_quiz_button.setMinimumSize(QtCore.QSize(0, 50))
        self.restart_quiz_button.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.restart_quiz_button.setObjectName("restart_quiz_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.restart_quiz_button)
        self.label_4 = QtWidgets.QLabel(self.quiz_left_frame)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.label_project_nav = QtWidgets.QLabel(self.quiz_left_frame)
        self.label_project_nav.setWordWrap(True)
        self.label_project_nav.setObjectName("label_project_nav")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_project_nav)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem14)
        self.main_list_widget = QtWidgets.QListWidget(self.quiz_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_list_widget.sizePolicy().hasHeightForWidth())
        self.main_list_widget.setSizePolicy(sizePolicy)
        self.main_list_widget.setMinimumSize(QtCore.QSize(81, 0))
        self.main_list_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_list_widget.setLineWidth(3)
        self.main_list_widget.setObjectName("main_list_widget")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.main_list_widget)
        self.change_quiz_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.change_quiz_button.setObjectName("change_quiz_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.change_quiz_button)
        self.go_to_questionnare_button = QtWidgets.QPushButton(self.quiz_left_frame)
        self.go_to_questionnare_button.setObjectName("go_to_questionnare_button")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.go_to_questionnare_button)
        self.label_3.raise_()
        self.new_quiz_button.raise_()
        self.restart_quiz_button.raise_()
        self.label_4.raise_()
        self.label_project_nav.raise_()
        self.main_list_widget.raise_()
        self.change_quiz_button.raise_()
        self.go_to_questionnare_button.raise_()
        self.gridLayout_2.addWidget(self.quiz_left_frame, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.quiz_main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        QuizMainWindow.setCentralWidget(self.quiz_main_widget)
        self.quiz_menu_bar = QtWidgets.QMenuBar(QuizMainWindow)
        self.quiz_menu_bar.setGeometry(QtCore.QRect(0, 0, 688, 21))
        self.quiz_menu_bar.setObjectName("quiz_menu_bar")
        QuizMainWindow.setMenuBar(self.quiz_menu_bar)
        self.quiz_status_bar = QtWidgets.QStatusBar(QuizMainWindow)
        self.quiz_status_bar.setObjectName("quiz_status_bar")
        QuizMainWindow.setStatusBar(self.quiz_status_bar)
        self.quiz_tool_bar = QtWidgets.QToolBar(QuizMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quiz_tool_bar.sizePolicy().hasHeightForWidth())
        self.quiz_tool_bar.setSizePolicy(sizePolicy)
        self.quiz_tool_bar.setObjectName("quiz_tool_bar")
        QuizMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.quiz_tool_bar)

        self.textify(QuizMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QuizMainWindow)

    def textify(self, QuizMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QuizMainWindow.setWindowTitle(_translate("QuizMainWindow", "MainWindow"))
        self.answer_a_button.setText(_translate("QuizMainWindow", "Answer a)"))
        self.label_a.setText(_translate("QuizMainWindow", "a)"))
        self.label_possible_answers.setText(_translate("QuizMainWindow", "Possible Answers"))
        self.label_number_questions.setText(_translate("QuizMainWindow", "# of questions:"))
        self.label_quiz_details.setText(_translate("QuizMainWindow", "Quiz Details:"))
        self.label_d.setText(_translate("QuizMainWindow", "d)"))
        self.Answer_b_button.setText(_translate("QuizMainWindow", "Answer b)"))
        self.answer_c_button.setText(_translate("QuizMainWindow", "Answer c)"))
        self.label_project_title_questionnare.setText(_translate("QuizMainWindow", "Quiz Title"))
        self.label_question.setText(_translate("QuizMainWindow", "Question:"))
        self.label_c.setText(_translate("QuizMainWindow", "c)"))
        item = self.quiz_stats_table.horizontalHeaderItem(0)
        item.setText(_translate("QuizMainWindow", "Questions"))
        item = self.quiz_stats_table.horizontalHeaderItem(1)
        item.setText(_translate("QuizMainWindow", "Answered"))
        item = self.quiz_stats_table.horizontalHeaderItem(2)
        item.setText(_translate("QuizMainWindow", "Percentage"))
        item = self.quiz_stats_table.horizontalHeaderItem(3)
        item.setText(_translate("QuizMainWindow", "Percentage Correct"))
        self.answer_d_button.setText(_translate("QuizMainWindow", "Answer d)"))
        self.label_stats.setText(_translate("QuizMainWindow", "Stats"))
        self.label_b.setText(_translate("QuizMainWindow", "b)"))
        self.label_average_difficulty.setText(_translate("QuizMainWindow", "Average Difficulty:"))
        self.label_tags_question.setText(_translate("QuizMainWindow", "Tags"))
        self.cancel_quiz_button.setText(_translate("QuizMainWindow", "(X) Cancel"))
        self.dinish_quiz_button.setText(_translate("QuizMainWindow", "(✓) Finish Quiz"))
        self.label_tag_1.setText(_translate("QuizMainWindow", "Tag 1"))
        self.label_tag_2.setText(_translate("QuizMainWindow", "Tag 2"))
        self.new_quiz_button.setText(_translate("QuizMainWindow", "(+)"))
        self.label_3.setText(_translate("QuizMainWindow", "New Quiz \n"
                                                          "(This goes first!)"))
        self.restart_quiz_button.setText(_translate("QuizMainWindow", "(<--)"))
        self.label_4.setText(_translate("QuizMainWindow", "Restart current Quiz"))
        self.label_project_nav.setText(_translate("QuizMainWindow", "Click here to navigate through projects:"))
        self.change_quiz_button.setText(_translate("QuizMainWindow", "Change current quiz"))
        self.go_to_questionnare_button.setText(_translate("QuizMainWindow", "Lets prepare more\n"
                                                                            " Questionnares!"))
        self.quiz_tool_bar.setWindowTitle(_translate("QuizMainWindow", "toolBar"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QuizMainWindow = QtWidgets.QMainWindow()
    ui = UiQuizMainWindow()
    ui.__init__()
    QuizMainWindow.show()
    sys.exit(app.exec_())
